IMAGENET:
  GET_ACCURACY_ONLY: False
  DATASETS:
    PATH_TO_IMAGENET: '/home/guy.b/Desktop/imagenet/val'
    PATH_TO_IMAGENET_O: '/home/guy.b/Desktop/imagenet_o'
    PATH_TO_IMAGENET_A: '/home/guy.b/Desktop/imagenet_a'
    GENERATING_OOD:
      FGSM:
        EPS: 0.0001
        BATCH_SIZE: 8

      CW:
        C: 0.00000005 
        KAPPA: 0
        STEPS: 10 # 1000
        LR: 0.01 

      PGD:
        EPS: 0.0001
        STEPS: 10 # 10
        ALPHA: 0.0001
        RANDOM_START: True

      GAUSS_NOISE:
        STD: 0.1 # 0.01, 0.02, 0.03, 0.04, 0.05

      ROTATE:
        ANGLE: 25 # 2, 5, 10, 15, 20, 25

      ZOOM:
        FACTOR: 0.9 # 1.3, 1.2, 1.1, 1.05, 0.95, 0.9, 0.8, 0.7

  EXPERIMENT:
    SEED: 42
    OOD: 'imagenet_o'
    MMD_FIT_SIZE: 1000
    KS_FIT_SIZE: 49000
    TRAIN_SIZE: 49000
    NUM_RANDOM_RUNS: 3 # 15
    NUM_BOOTSTRAP_RUNS: 100
    WINDOW_SIZES: [ 10, 20, 50, 100, 200, 500, 1000 ]
    DETECTORS: [ 'my_detector']
    #DETECTORS: [ 'my_detector', 'drift_ks_embs', 'drift_ks_logits', 'drift_ks_softmaxes',
     #             'drift_mmd_embs', 'drift_mmd_logits', 'drift_mmd_softmaxes', 'drift_single_softmaxes', 'drift_single_entropies' ]
    PATH_TO_RESULTS: '/home/guy.b/Window-Based-Distribution-Shift-Detection/imagenet_experiments'

  MODEL: 'resnet50'
  PATH_TO_SAVE_OUTPUTS: '/home/guy.b/Window-Based-Distribution-Shift-Detection/outputs' # '/home/guy.b/code_updated/outputs'
  BATCH_SIZE: 64
  PATH_TO_SAVE_ACCURACIES: '/home/guy.b/Window-Based-Distribution-Shift-Detection/imagenet_experiments/imagenet/accuracies.csv' # '/home/guy.b/code_updated/imagenet_experiments/imagenet/accuracies.csv'
  DEVICE_INDEX: 0
  NUM_WORKERS: 8

MY_DETECTOR:
  C_NUM: 10
  DELTA: 0.01
  TEMP: 1.0
  UC_MECH: 'Ent'
  SIGNIFICANCE_LEVEL: 0.05

